version: "3.6"
services:
    app:
        build:
            context: .
            target: development
        depends_on:
            - db

        volumes:
            - ./src:/app/src
            - ./prisma:/app/prisma
        ports:
            - 3000:3000
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
            - NODE_ENV=development
            - SECRET=secret
    db:
        image: postgres:14
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: dev
    migratedb:
        image: app:latest
        command:
            [
                "./wait-for-it/wait-for-it.sh",
                "db:5432",
                "--",
                "npx",
                "prisma",
                "migrate",
                "deploy",
            ]
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
        build:
            context: .
            target: development
